# fly.toml app configuration file generated for bidhive on 2025-10-06T11:52:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bidhive'
primary_region = 'iad'
kill_signal = 'SIGTERM'
kill_timeout = '10s'

[build]

[deploy]
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  app = 'node dist/index.js'

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/api/health/live'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
